---
- hosts: jenkinsserver
  # become: yes
  gather_facts: false
  
  roles:
   - role: delete
     tags:
      - clean_files
   - role: copy
     tags:
      - copy_files
   - role: filepermission
     tags:
      - chmod_operation
   - role: ebDeploy
     tags:
      - ebdeploy   
   
  #  - role: delete
  #    tags:
  #     - gitAddCommit
  