---
- hosts: jenkinsserver
  become: yes
  gather_facts: false
  
  roles:
   - role: delete
     tags:
      - clean_files
   - role: copy
     tags:
      - copy_files
   - role: filepermission
     tags:
      - chmod_operation   
   
  #  - role: delete
  #    tags:
  #     - gitAddCommit
  #  - role: ebDeploy
  #    tags:
  #     - ebdeploy