---
- hosts: jenkinsserver
  become: yes
  gather_facts: false
  
  roles:
   - role: 
      - delete
      - copy
      - gitAddCommit
     tags:
      - copy_files
      - clean_files
      - git_checkout

   - role:
      - ebDeploy
     tags:
      - ebdeploy
  
  
 