---
- hosts: jenkinsserver
  become: yes
  gather_facts: false
  
  roles:
   - role: copy
     tags:
      - copy_files
   - role: delete
     tags:
      - clean_files
   - role: delete
     tags:
      - gitAddCommit
   - role: ebDeploy
     tags:
      - ebdeploy