---
- name: Ensure httpd is running
  service:
    name: apache2 
    state: started

- name: Open port 80 for http access
  firewalld:
    service: apache2
    permanent: true
    state: enabled

- name: Restart the firewalld service to load in the firewall changes
  service: 
    name: firewalld 
    state: restarted