# - name: Move html js files from public to build directory
#   command: mv "/opt/test1/{{ item }}" "/opt/test1/build_archive"      
#   with_items:
#         - "build/"
#         - "package.json"
#         - "package-lock.json"
#         - "public/"
#         - "src/"
#   tags:
#    - ebdeploy

- name: eb deployment to elastic beanstalk
  become: true
  become_method: sudo
  become_flags: 'su - root /home/dradmin/test3 -c'
  # shell: '/opt/cicd_wrappers/files/ebdeploy_wraper.sh'
  # shell: cd /opt/test1 | git rm -r --cached venv | git commit -m 'Remove the now ignored directory venv' | git push origin master | eb deploy 
  shell: cd /home/dradmin/test3 | eb init --region ap-southeast-1 --platform Node.js test_app | eb list | eb deploy Testapp-env
  register: command_output
  tags:
   - ebdeploy
- debug:
    var: command_output.stdout_lines
  # args:
  #  chdir: /home/dradmin/test3
  tags:
   - ebdeploy

# - name: eb deployment to elastic beanstalk
#   shell: eb init
#   args:
#     chdir: /opt/test1/

# - name: eb deployment to elastic beanstalk
#   shell: eb deploy
#   args:
#     chdir: /opt/test1/
#   tags:
#    - ebdeploy