- name: eb deployment to elastic beanstalk
  shell: cd /opt/test1 | eb list 
  become: true
  # args:
  #   chdir: /opt/test1/
  tags:
   - ebdeploy

# - name: eb deployment to elastic beanstalk
#   shell: eb init
#   args:
#     chdir: /opt/test1/

# - name: eb deployment to elastic beanstalk
#   shell: eb deploy
#   args:
#     chdir: /opt/test1/
#   tags:
#    - ebdeploy