- name: eb deployment to elastic beanstalk
  # become: true
  # become_method: sudo
  # become_flags: 'su - root /opt/test1 -c'
  # shell: '/opt/cicd_wrappers/files/ebdeploy_wraper.sh'
  shell: cd /opt/test1 | eb deploy 
  register: command_output
- debug:
    var: command_output.stdout_lines
  # args:
  #   chdir: /opt/test1/
  tags:
   - ebdeploy

# - name: eb deployment to elastic beanstalk
#   shell: eb init
#   args:
#     chdir: /opt/test1/

# - name: eb deployment to elastic beanstalk
#   shell: eb deploy
#   args:
#     chdir: /opt/test1/
#   tags:
#    - ebdeploy