- name: eb deployment to elastic beanstalk
  # become: true
  # become_method: sudo
  # become_flags: 'su - root /opt/test1 -c'
  # shell: '/var/lib/jenkins/workspace/ravi/reactApp/kanth/roles/ebDeploy/files/ebdeploy_wraper.sh'



  shell: pwd | sudo su - | cd /opt/test1 | pwd | eb list 
  
  # args:
  #   chdir: /opt/test1/
  tags:
   - ebdeploy

# - name: eb deployment to elastic beanstalk
#   shell: eb init
#   args:
#     chdir: /opt/test1/

# - name: eb deployment to elastic beanstalk
#   shell: eb deploy
#   args:
#     chdir: /opt/test1/
#   tags:
#    - ebdeploy