- name: Give insecure permissions to an existing file
  file:
    path: /home/dradmin/test3/.elasticbeanstalk
    owner: root
    group: root
    mode: '1777'
  tags:
   - chmod_operation

-  name: Give insecure permissions to an existing file
   file:
    path: /home/dradmin/test3/.elasticbeanstalk/config.yml
    owner: root
    group: root
    mode: '1777'
  tags:
   - chmod_operation