- name: Give insecure permissions to an existing file
  file:
    path: /opt/test_app/.elasticbeanstalk
    owner: root
    group: root
    mode: '0777'
  tags:
   - chmod_operation

-  name: Give insecure permissions to an existing file
   file:
    path: /opt/test_app/.elasticbeanstalk/config.yml
    owner: root
    group: root
    mode: '0777'
   tags:
    - chmod_operation