- name: git add all new files
  shell: git add .
  args:
    chdir: /opt/test1/
  tags:
   - git_checkout

- name: git commit all new files
  shell: git commit -m "modified"
  args:
    chdir: /opt/test1/
  ignore_errors: true
  tags:
   - git_checkout