- name: copy 
  synchronize:
    src: "{{ src_dir }}"
    dest: "{{ dest_dir }}"
    rsync_opts:
        # - "--exclude=node_modules"
        - "--exclude=kanth"
        - "--exclude=.git"
        - "--exclude=.gitignore"
        - "--exclude=README.md"
        - "--exclude=kanth@tmp"
  tags:
      - copy_files
- name: infra files copy 
  synchronize:
    src: "{{ infra_src_dir }}"
    dest: "{{ infra_dst_dir }}"
    
  tags:
      - copy_files
