- name: copy 
  synchronize:
    src: /var/lib/jenkins/workspace/ravi/reactApp/
    dest: /opt/test1/
    rsync_opts:
        - "--exclude=node_modules"
        - "--exclude=kanth"
        - "--exclude=.git"
        - "--exclude=.gitignore"