- name: copy 
  synchronize:
    src: /var/lib/jenkins/workspace/ravi/reactApp/
    dest: /opt/test2/
    rsync_opts:
        - "--exclude=node_modules"
        - "--exclude=kanth"
        - "--exclude=.git"
        - "--exclude=.gitignore"
        - "--exclude=README.md"
        - "--exclude=kanth@tmp"
  tags:
      - copy_files